[package]
name = "aoc-any"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
itertools = "0.12"
ndarray = "0.15.6"
rayon = "1.10.0"
